# Docker volume (~mount):
# docker run -v /raid/utku/:/workspace -t pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
# You can also moun with ADD
# Docker cp to copy from local to docker running container.
# BASE IMAGE
ARG PYTORCH_VERSION="1.9.0"
ARG CUDA_VERSION="10.2"
ARG CUDNN_VERSION="7"
# FROM nvidia/cuda:11.3.1-base-ubuntu16.04
FROM pytorch/pytorch:${PYTORCH_VERSION}-cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}-runtime
# ENV DEBIAN_FRONTEND=noninteractive
ENV FORCE_CUDA="1"

# PYTHON DEPENDENCIES
ENV PYTHON_VERSION=3.6
ENV MMDETECTION_VERSION=2.16.0+fe46ffe
ENV MMCV_VERSION=1.3.9
ENV WANDB=0.10.31


# Apt installations.
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    gcc git tmux nano\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# RUN apt-get update
# RUN apt-get install software-properties-common -y
# RUN add-apt-repository ppa:deadsnakes/ppa
# RUN apt-get update
# RUN apt-get install python3.6 -y 

RUN python3 -V
# RUN apt-get install python3.6-dev
# RUN apt-get install python3.6-pip

# Install python packages ==${MMDETECTION_VERSION}
RUN pip3 install mmcv==${MMCV_VERSION} wandb==${WANDB}
# Install mmdetections
RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
WORKDIR /mmdetection
RUN pip3 install -r requirements/build.txt
RUN pip3 install --no-cache-dir -e .
ADD /raid/utku /workspace